# Example  .gitlab-ci.yml file
stages:
  - maventry

maven-build:   #this is a JOB
  stage: maventry
  tags:
    - springboot_tag  # this is LINK to the shell runner on the remote-server 
  script:
    - cd backend/backend
    - mvn package