# Example  .gitlab-ci.yml file
stages:
  - maven-test
  - android-build

maven-test:   #this is a JOB
  stage: maven-test
  tags:
    - springboot_tag  # this is LINK to the shell runner on the remote-server 
  script:
    - sudo systemctl start docker
    - cd backend/backend
    - mvn test
  artifacts:
    paths:
      - backend/backend/target/*.jar

android-build:
  image: gjandres/android-ci:latest
  stage: android-build
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./frontend/LoginTest/gradlew
  tags:
   - android_tag
  script:
    - cd frontend/LoginTest
    - ./gradlew build
  artifacts:
    paths:
    - Android_test/app/build/outputs/